apiVersion: v1
kind: Service
metadata:
  name: editorzzz-service
spec:
  type: NodePort
  selector:
    app: editorzzz
  ports:
    - name: backend
      port: 1001       
      targetPort: 1001 
      nodePort: 30007  

    - name: client
      port: 4000       
      targetPort: 4000 
      nodePort: 30008  