sonar.projectKey=ayushmehta03_editorzzAdmin
sonar.organization=ayushmehta03

sonar.sources=backend

sonar.exclusions=client/**,**/vendor/**,**/build-wrapper-dump.json

sonar.go.coverage.reportPaths=backend/coverage.out