sonar.projectKey=ayushmehta03_editorzzAdmin

sonar.sources=backend

sonar.exclusions=client/**,**/vendor/**,**/build-wrapper-dump.json

sonar.go.coverage.reportPaths=backend/coverage.out

sonar.coverage.exclusions=**/*_test.go