name: Backend Api Builder and Tester
on: [push]

# simple file it will get the dependency , build the golang code and test it with unti tests written
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Setup Golang


              uses: actions/setup-go@v5


              with:
                  go-version: 1.25.1


            - name: install dep
              run: go get .


            - name: Build Gocode
              run: go build -v ./backend


            - name: test golang controllers
              run: go test

    