name: SonarCloud SAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarCloud SAST Analysis
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Java for Sonar
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
          cache: true
          cache-dependency-path: backend/go.sum

      # Verify Go installation
      - name: Verify Go
        run: |
          go version
          which go
          go env GOROOT
          go env GOTOOLDIR

      # Download dependencies
      - name: Download Go dependencies
        working-directory: ./backend
        run: go mod download

      # Run tests
      - name: Run Go tests
        working-directory: ./backend
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        run: |
          go test ./...

      # SonarCloud SAST
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ayushmehta03_editorzzAdmin
            -Dsonar.organization=ayushmehta03
            -Dsonar.sources=backend
            -Dsonar.exclusions=client/**,**/vendor/**,**/build-wrapper-dump.json

      # Quality Gate
      - name: SonarCloud Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}